package main

import (
	"log"
	"lunch_menu/internal/config"
	"lunch_menu/internal/database"
	"lunch_menu/internal/middleware"
	"lunch_menu/internal/routes"
	"os"

	_ "lunch_menu/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	// Load configuration
	config.MustLoadConfig()

	// Initialize database
	if err := database.InitDatabase(); err != nil {
		log.Fatalf("DB init failed: %v", err)
	}
	if err := database.Migrate(); err != nil {
		log.Fatalf("DB migration failed: %v", err)
	}
	defer database.CloseDatabase()

	// Create Gin router
	router := gin.Default()

	// Clean: Use rate limiting middleware from your package
	router.Use(middleware.RateLimitMiddleware("10-S"))

	//will apply CSRF checks to all requests that match the HTTP methods you specify in the middleware (usually POST, PUT, PATCH, DELETE).
	// router.Use(middleware.CSRFProtection())

	// Use gin-contrib/cors middleware
	corsConfig := cors.DefaultConfig()
	corsConfig.AllowAllOrigins = true //  should restrict AllowAllOrigins for security in production
	corsConfig.AllowCredentials = true
	corsConfig.AllowMethods = []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}
	corsConfig.AllowHeaders = []string{"*"}
	router.Use(cors.New(corsConfig))

	// CORS does not affect Postman or server-to-server requests. It is safe to enable for APIs, but you should restrict Access-Control-Allow-Origin in production.
	// router.Use(middleware.CORSMiddleware())

	// Setup all routes and middleware
	routes.SetupRoutes(router)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Get port from environment or default to 8000
	port := os.Getenv("PORT")
	if port == "" {
		port = "8000"
	}

	log.Printf("Starting Restaurant Management API on port %s", port)
	log.Printf("Swagger documentation available at: http://localhost:%s/swagger/index.html#/", port)
	// log.Printf("API endpoints:")
	// log.Printf("  GET    /api")
	// log.Printf("  GET    /api/restaurants")
	// log.Printf("  GET    /api/restaurants/:id")
	// log.Printf("  GET    /api/restaurants/:id/menu")
	// log.Printf("  GET    /api/menu-items/:id")
	// log.Printf("  GET    /api/stats")

	if err := router.Run(":" + port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
